name: build project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  push:
    paths:
      - '.github/workflows/build-project.yml'

jobs:
  build-on-host:
    runs-on: ubuntu-latest
    steps:
    - name: Build on host
      run: |
        sudo apt-get update && \
        mkdir ${HOME}/project && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build gcc ------------------------------\033[0m" && \
        sudo apt-get install -y git g++ libmpc-dev make flex && \
        git clone https://github.com/gcc-mirror/gcc.git && \
        cd gcc && \
        mkdir build && \
        cd build && \
        ../configure --disable-multilib && \
        make -j$(nproc) && \
        echo -e "\033[32m${HOME}/project/gcc/build/gcc/xg++ --version:\033[0m" && \
        ${HOME}/project/gcc/build/gcc/xg++ --version && \
        echo $'#include <bits/stdc++.h>\nint main() {\n    std::cout << "Hello World!" << std::endl;\n    return 0;\n}' > ${HOME}/project/main.cpp && \
        ${HOME}/project/gcc/build/gcc/xg++ \
          -B${HOME}/project/gcc/build/gcc \
          -I${HOME}/project/gcc/build/x86_64-pc-linux-gnu/libstdc++-v3/include \
          -I${HOME}/project/gcc/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu \
          -I${HOME}/project/gcc/libstdc++-v3/libsupc++ \
          -L${HOME}/project/gcc/build/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs \
          -o ${HOME}/project/a.out \
          ${HOME}/project/main.cpp && \
        ${HOME}/project/a.out && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build clang ------------------------------\033[0m" && \
        sudo apt-get install -y git g++ cmake ninja-build python3 && \
        git clone https://github.com/llvm/llvm-project.git && \
        cd llvm-project && \
        mkdir build && \
        cd build && \
        cmake -G Ninja ../llvm -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_PROJECTS="clang" \
          -DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind;libcxxabi;libcxx" && \
        ninja && \
        echo -e "\033[32m${HOME}/project/llvm-project/build/bin/clang --version:\033[0m" && \
        ${HOME}/project/llvm-project/build/bin/clang --version && \
        cat << 'EOF' > ${HOME}/project/main.cpp
        #include <iostream>
        int main() {
            std::cout << "Hello World!" << std::endl;
            return 0;
        }
        EOF
        ${HOME}/project/llvm-project/build/bin/clang++ -o ${HOME}/project/a.out ${HOME}/project/main.cpp && \
        ${HOME}/project/a.out && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build cgdb ------------------------------\033[0m" && \
        sudo apt-get install -y git g++ automake make flex texinfo libreadline-dev gdb && \
        git clone https://github.com/cgdb/cgdb.git && \
        cd cgdb && \
        ./autogen.sh && \
        mkdir build && \
        cd build && \
        ../configure && \
        make -j$(nproc) && \
        echo -e "\033[32m${HOME}/project/cgdb/build/cgdb/cgdb --version:\033[0m" && \
        ${HOME}/project/cgdb/build/cgdb/cgdb --version && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build cpython ------------------------------\033[0m" && \
        sudo apt-get install -y git build-essential gdb lcov pkg-config \
              libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
              libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
              lzma lzma-dev tk-dev uuid-dev zlib1g-dev libzstd-dev \
              inetutils-inetd && \
        git clone https://github.com/python/cpython.git && \
        cd cpython && \
        mkdir build && \
        cd build && \
        ../configure --with-pydebug && \
        make -j$(nproc) && \
        echo -e "\033[32m${HOME}/project/cpython/build/python --version:\033[0m" && \
        ${HOME}/project/cpython/build/python --version && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build LearnOpenGL ------------------------------\033[0m" && \
        sudo apt-get install -y git g++ cmake libsoil-dev libglm-dev libassimp-dev libglew-dev libglfw3-dev libxinerama-dev libxcursor-dev  libxi-dev libfreetype-dev libgl1-mesa-dev xorg-dev && \
        git clone https://github.com/JoeyDeVries/LearnOpenGL.git && \
        cd LearnOpenGL && \
        mkdir build && \
        cd build && \
        cmake .. && \
        cmake --build . && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ download go ------------------------------\033[0m" && \
        sudo apt-get install -y curl && \
        go_version='1.23.1' && \
        curl -L -O https://go.dev/dl/go${go_version}.linux-amd64.tar.gz && \
        tar -zxf go${go_version}.linux-amd64.tar.gz && \
        rm go${go_version}.linux-amd64.tar.gz && \
        export PATH=${HOME}/project/go/bin:$PATH && \
        echo -e "\033[32mgo version:\033[0m" && \
        go version && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build xray ------------------------------\033[0m" && \
        sudo apt-get install -y git && \
        git clone https://github.com/XTLS/Xray-core.git && \
        cd Xray-core && \
        go mod download && \
        CGO_ENABLED=0 go build -o xray -trimpath -ldflags "-s -w -buildid=" ./main && \
        echo -e "\033[32m${HOME}/project/Xray-core/xray version:\033[0m" && \
        ${HOME}/project/Xray-core/xray version && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ download c-plus-plus-primer ------------------------------\033[0m" && \
        sudo apt-get install -y curl unzip && \
        curl -L -O https://www.informit.com/content/images/9780321714114/downloads/GCC_pre_C11.zip && \
        unzip -q GCC_pre_C11.zip -d c-plus-plus-primer && \
        rm GCC_pre_C11.zip && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ download telegram ------------------------------\033[0m" && \
        sudo apt-get install -y curl aapt && \
        curl -L -O https://telegram.org/dl/android/apk && \
        echo -e "\033[32maapt dump badging apk | grep versionName:\033[0m" && \
        aapt dump badging apk | grep versionName && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ download dotnet ------------------------------\033[0m" && \
        sudo apt-get install -y curl libicu74 && \
        dotnet_sdk_version='10.0.102' && \
        curl -L -O https://builds.dotnet.microsoft.com/dotnet/Sdk/${dotnet_sdk_version}/dotnet-sdk-${dotnet_sdk_version}-linux-x64.tar.gz && \
        DOTNET_FILE=dotnet-sdk-${dotnet_sdk_version}-linux-x64.tar.gz && \
        export DOTNET_ROOT=$(pwd)/.dotnet && \
        mkdir -p "$DOTNET_ROOT" && \
        tar zxf "$DOTNET_FILE" -C "$DOTNET_ROOT" && \
        rm $DOTNET_FILE && \
        export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools && \
        echo -e "\033[32mdotnet --version:\033[0m" && \
        dotnet --version && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build v2rayN ------------------------------\033[0m" && \
        sudo apt-get install -y git wget 7zip && \
        git clone --recursive https://github.com/2dust/v2rayN.git && \
        cd ${HOME}/project/v2rayN/v2rayN && \
        echo -e "\033[32m------------------------------ build windows desktop ------------------------------\033[0m" && \
        OutputArch="windows-64" && \
        OutputArchArm="windows-arm64" && \
        OutputPath64="${HOME}/project/v2rayN/Release/windows-desktop-64" && \
        OutputPathArm64="${HOME}/project/v2rayN/Release/windows-desktop-arm64" && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r win-x64   -p:SelfContained=true -p:EnableWindowsTargeting=true -o $OutputPath64 && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r win-arm64 -p:SelfContained=true -p:EnableWindowsTargeting=true -o $OutputPathArm64 && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r win-x64   -p:SelfContained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o $OutputPath64 && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r win-arm64 -p:SelfContained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o $OutputPathArm64 && \
        cd ${HOME}/project/v2rayN && \
        echo -e "\033[32m------------------------------ package release zip archive ------------------------------\033[0m" && \
        chmod 755 package-release-zip.sh && \
        ./package-release-zip.sh $OutputArch $OutputPath64 && \
        mv "v2rayN-${OutputArch}.zip" "v2rayN-${OutputArch}-desktop.zip" && \
        ./package-release-zip.sh $OutputArchArm $OutputPathArm64 && \
        mv "v2rayN-${OutputArchArm}.zip" "v2rayN-${OutputArchArm}-desktop.zip" && \
        mv v2rayN-windows-64 v2rayN-windows-64-desktop && \
        mv v2rayN-windows-arm64 v2rayN-windows-arm64-desktop && \
        cd ${HOME}/project/v2rayN/v2rayN && \
        echo -e "\033[32m------------------------------ build windows ------------------------------\033[0m" && \
        OutputArch="windows-64" && \
        OutputArchArm="windows-arm64" && \
        OutputPath64="${HOME}/project/v2rayN/Release/windows-64" && \
        OutputPathArm64="${HOME}/project/v2rayN/Release/windows-arm64" && \
        dotnet publish ./v2rayN/v2rayN.csproj     -c Release -r win-x64   -p:SelfContained=true -p:EnableWindowsTargeting=true -o $OutputPath64 && \
        dotnet publish ./v2rayN/v2rayN.csproj     -c Release -r win-arm64 -p:SelfContained=true -p:EnableWindowsTargeting=true -o $OutputPathArm64 && \
        dotnet publish ./AmazTool/AmazTool.csproj -c Release -r win-x64   -p:SelfContained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o $OutputPath64 && \
        dotnet publish ./AmazTool/AmazTool.csproj -c Release -r win-arm64 -p:SelfContained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o $OutputPathArm64 && \
        cd ${HOME}/project/v2rayN && \
        echo -e "\033[32m------------------------------ package release zip archive ------------------------------\033[0m" && \
        chmod 755 package-release-zip.sh && \
        ./package-release-zip.sh $OutputArch $OutputPath64 && \
        ./package-release-zip.sh $OutputArchArm $OutputPathArm64 && \
        cd ${HOME}/project/v2rayN/v2rayN && \
        echo -e "\033[32m------------------------------ build linux ------------------------------\033[0m" && \
        OutputArch="linux-64" && \
        OutputArchArm="linux-arm64" && \
        OutputPath64="${HOME}/project/v2rayN/Release/linux-64" && \
        OutputPathArm64="${HOME}/project/v2rayN/Release/linux-arm64" && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r linux-x64   -p:SelfContained=true -o "$OutputPath64" && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r linux-arm64 -p:SelfContained=true -o "$OutputPathArm64" && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r linux-x64   -p:SelfContained=true -p:PublishTrimmed=true -o "$OutputPath64" && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r linux-arm64 -p:SelfContained=true -p:PublishTrimmed=true -o "$OutputPathArm64" && \
        cd ${HOME}/project/v2rayN && \
        echo -e "\033[32m------------------------------ package debian ------------------------------\033[0m" && \
        release_tag="1.0.0" && \
        chmod 755 package-debian.sh && \
        ./package-debian.sh $OutputArch $OutputPath64 ${release_tag} && \
        ./package-debian.sh $OutputArchArm $OutputPathArm64 ${release_tag} && \
        echo -e "\033[32m------------------------------ package release zip archive ------------------------------\033[0m" && \
        chmod 755 package-release-zip.sh && \
        ./package-release-zip.sh $OutputArch $OutputPath64 && \
        ./package-release-zip.sh $OutputArchArm $OutputPathArm64 && \
        cd ${HOME}/project/v2rayN/v2rayN && \
        echo -e "\033[32m------------------------------ build osx ------------------------------\033[0m" && \
        OutputArch="macos-64" && \
        OutputArchArm="macos-arm64" && \
        OutputPath64="${HOME}/project/v2rayN/Release/macos-64" && \
        OutputPathArm64="${HOME}/project/v2rayN/Release/macos-arm64" && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r osx-x64   -p:SelfContained=true -o $OutputPath64 && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r osx-arm64 -p:SelfContained=true -o $OutputPathArm64 && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r osx-x64   -p:SelfContained=true -p:PublishTrimmed=true -o $OutputPath64 && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r osx-arm64 -p:SelfContained=true -p:PublishTrimmed=true -o $OutputPathArm64 && \
        cd ${HOME}/project/v2rayN && \
        echo -e "\033[32m------------------------------ package release zip archive ------------------------------\033[0m" && \
        chmod 755 package-release-zip.sh && \
        ./package-release-zip.sh $OutputArch $OutputPath64 && \
        ./package-release-zip.sh $OutputArchArm $OutputPathArm64 && \
        echo -e "\033[32mls -AlhF ${HOME}/project/v2rayN:\033[0m" && \
        ls -AlhF ${HOME}/project/v2rayN && \
        cd ${HOME}/project

  build-in-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Build in docker
      run: |
        cat << 'SCRIPT' > build-project.sh
        apt-get update && \
        apt-get upgrade -y && \
        echo -e "\n5\n69" | apt-get install -y tzdata && \
        apt-get install -y sudo && \
        sudo apt-get update && \
        mkdir ${HOME}/project && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build gcc ------------------------------\033[0m" && \
        sudo apt-get install -y git g++ libmpc-dev make flex && \
        git clone https://github.com/gcc-mirror/gcc.git && \
        cd gcc && \
        mkdir build && \
        cd build && \
        ../configure --disable-multilib && \
        make -j$(nproc) && \
        echo -e "\033[32m${HOME}/project/gcc/build/gcc/xg++ --version:\033[0m" && \
        ${HOME}/project/gcc/build/gcc/xg++ --version && \
        echo $'#include <bits/stdc++.h>\nint main() {\n    std::cout << "Hello World!" << std::endl;\n    return 0;\n}' > ${HOME}/project/main.cpp && \
        ${HOME}/project/gcc/build/gcc/xg++ \
          -B${HOME}/project/gcc/build/gcc \
          -I${HOME}/project/gcc/build/x86_64-pc-linux-gnu/libstdc++-v3/include \
          -I${HOME}/project/gcc/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu \
          -I${HOME}/project/gcc/libstdc++-v3/libsupc++ \
          -L${HOME}/project/gcc/build/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs \
          -o ${HOME}/project/a.out \
          ${HOME}/project/main.cpp && \
        ${HOME}/project/a.out && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build clang ------------------------------\033[0m" && \
        sudo apt-get install -y git g++ cmake ninja-build python3 && \
        git clone https://github.com/llvm/llvm-project.git && \
        cd llvm-project && \
        mkdir build && \
        cd build && \
        cmake -G Ninja ../llvm -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_PROJECTS="clang" \
          -DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind;libcxxabi;libcxx" && \
        ninja && \
        echo -e "\033[32m${HOME}/project/llvm-project/build/bin/clang --version:\033[0m" && \
        ${HOME}/project/llvm-project/build/bin/clang --version && \
        cat << 'EOF' > ${HOME}/project/main.cpp
        #include <iostream>
        int main() {
            std::cout << "Hello World!" << std::endl;
            return 0;
        }
        EOF
        ${HOME}/project/llvm-project/build/bin/clang++ -o ${HOME}/project/a.out ${HOME}/project/main.cpp && \
        ${HOME}/project/a.out && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build cgdb ------------------------------\033[0m" && \
        sudo apt-get install -y git g++ automake make flex texinfo libreadline-dev gdb && \
        git clone https://github.com/cgdb/cgdb.git && \
        cd cgdb && \
        ./autogen.sh && \
        mkdir build && \
        cd build && \
        ../configure && \
        make -j$(nproc) && \
        echo -e "\033[32m${HOME}/project/cgdb/build/cgdb/cgdb --version:\033[0m" && \
        ${HOME}/project/cgdb/build/cgdb/cgdb --version && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build cpython ------------------------------\033[0m" && \
        sudo apt-get install -y git build-essential gdb lcov pkg-config \
              libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
              libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
              lzma lzma-dev tk-dev uuid-dev zlib1g-dev libzstd-dev \
              inetutils-inetd && \
        git clone https://github.com/python/cpython.git && \
        cd cpython && \
        mkdir build && \
        cd build && \
        ../configure --with-pydebug && \
        make -j$(nproc) && \
        echo -e "\033[32m${HOME}/project/cpython/build/python --version:\033[0m" && \
        ${HOME}/project/cpython/build/python --version && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build LearnOpenGL ------------------------------\033[0m" && \
        sudo apt-get install -y git g++ cmake libsoil-dev libglm-dev libassimp-dev libglew-dev libglfw3-dev libxinerama-dev libxcursor-dev  libxi-dev libfreetype-dev libgl1-mesa-dev xorg-dev && \
        git clone https://github.com/JoeyDeVries/LearnOpenGL.git && \
        cd LearnOpenGL && \
        mkdir build && \
        cd build && \
        cmake .. && \
        cmake --build . && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ download go ------------------------------\033[0m" && \
        sudo apt-get install -y curl && \
        go_version='1.23.1' && \
        curl -L -O https://go.dev/dl/go${go_version}.linux-amd64.tar.gz && \
        tar -zxf go${go_version}.linux-amd64.tar.gz && \
        rm go${go_version}.linux-amd64.tar.gz && \
        export PATH=${HOME}/project/go/bin:$PATH && \
        echo -e "\033[32mgo version:\033[0m" && \
        go version && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build xray ------------------------------\033[0m" && \
        sudo apt-get install -y git && \
        git clone https://github.com/XTLS/Xray-core.git && \
        cd Xray-core && \
        go mod download && \
        CGO_ENABLED=0 go build -o xray -trimpath -ldflags "-s -w -buildid=" ./main && \
        echo -e "\033[32m${HOME}/project/Xray-core/xray version:\033[0m" && \
        ${HOME}/project/Xray-core/xray version && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ download c-plus-plus-primer ------------------------------\033[0m" && \
        sudo apt-get install -y curl unzip && \
        curl -L -O https://www.informit.com/content/images/9780321714114/downloads/GCC_pre_C11.zip && \
        unzip -q GCC_pre_C11.zip -d c-plus-plus-primer && \
        rm GCC_pre_C11.zip && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ download telegram ------------------------------\033[0m" && \
        sudo apt-get install -y curl aapt && \
        curl -L -O https://telegram.org/dl/android/apk && \
        echo -e "\033[32maapt dump badging apk | grep versionName:\033[0m" && \
        aapt dump badging apk | grep versionName && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ download dotnet ------------------------------\033[0m" && \
        sudo apt-get install -y curl libicu74 && \
        dotnet_sdk_version='10.0.102' && \
        curl -L -O https://builds.dotnet.microsoft.com/dotnet/Sdk/${dotnet_sdk_version}/dotnet-sdk-${dotnet_sdk_version}-linux-x64.tar.gz && \
        DOTNET_FILE=dotnet-sdk-${dotnet_sdk_version}-linux-x64.tar.gz && \
        export DOTNET_ROOT=$(pwd)/.dotnet && \
        mkdir -p "$DOTNET_ROOT" && \
        tar zxf "$DOTNET_FILE" -C "$DOTNET_ROOT" && \
        rm $DOTNET_FILE && \
        export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools && \
        echo -e "\033[32mdotnet --version:\033[0m" && \
        dotnet --version && \
        cd ${HOME}/project && \
        echo -e "\033[32m------------------------------ build v2rayN ------------------------------\033[0m" && \
        sudo apt-get install -y git wget 7zip && \
        git clone --recursive https://github.com/2dust/v2rayN.git && \
        cd ${HOME}/project/v2rayN/v2rayN && \
        echo -e "\033[32m------------------------------ build windows desktop ------------------------------\033[0m" && \
        OutputArch="windows-64" && \
        OutputArchArm="windows-arm64" && \
        OutputPath64="${HOME}/project/v2rayN/Release/windows-desktop-64" && \
        OutputPathArm64="${HOME}/project/v2rayN/Release/windows-desktop-arm64" && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r win-x64   -p:SelfContained=true -p:EnableWindowsTargeting=true -o $OutputPath64 && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r win-arm64 -p:SelfContained=true -p:EnableWindowsTargeting=true -o $OutputPathArm64 && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r win-x64   -p:SelfContained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o $OutputPath64 && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r win-arm64 -p:SelfContained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o $OutputPathArm64 && \
        cd ${HOME}/project/v2rayN && \
        echo -e "\033[32m------------------------------ package release zip archive ------------------------------\033[0m" && \
        chmod 755 package-release-zip.sh && \
        ./package-release-zip.sh $OutputArch $OutputPath64 && \
        mv "v2rayN-${OutputArch}.zip" "v2rayN-${OutputArch}-desktop.zip" && \
        ./package-release-zip.sh $OutputArchArm $OutputPathArm64 && \
        mv "v2rayN-${OutputArchArm}.zip" "v2rayN-${OutputArchArm}-desktop.zip" && \
        mv v2rayN-windows-64 v2rayN-windows-64-desktop && \
        mv v2rayN-windows-arm64 v2rayN-windows-arm64-desktop && \
        cd ${HOME}/project/v2rayN/v2rayN && \
        echo -e "\033[32m------------------------------ build windows ------------------------------\033[0m" && \
        OutputArch="windows-64" && \
        OutputArchArm="windows-arm64" && \
        OutputPath64="${HOME}/project/v2rayN/Release/windows-64" && \
        OutputPathArm64="${HOME}/project/v2rayN/Release/windows-arm64" && \
        dotnet publish ./v2rayN/v2rayN.csproj     -c Release -r win-x64   -p:SelfContained=true -p:EnableWindowsTargeting=true -o $OutputPath64 && \
        dotnet publish ./v2rayN/v2rayN.csproj     -c Release -r win-arm64 -p:SelfContained=true -p:EnableWindowsTargeting=true -o $OutputPathArm64 && \
        dotnet publish ./AmazTool/AmazTool.csproj -c Release -r win-x64   -p:SelfContained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o $OutputPath64 && \
        dotnet publish ./AmazTool/AmazTool.csproj -c Release -r win-arm64 -p:SelfContained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o $OutputPathArm64 && \
        cd ${HOME}/project/v2rayN && \
        echo -e "\033[32m------------------------------ package release zip archive ------------------------------\033[0m" && \
        chmod 755 package-release-zip.sh && \
        ./package-release-zip.sh $OutputArch $OutputPath64 && \
        ./package-release-zip.sh $OutputArchArm $OutputPathArm64 && \
        cd ${HOME}/project/v2rayN/v2rayN && \
        echo -e "\033[32m------------------------------ build linux ------------------------------\033[0m" && \
        OutputArch="linux-64" && \
        OutputArchArm="linux-arm64" && \
        OutputPath64="${HOME}/project/v2rayN/Release/linux-64" && \
        OutputPathArm64="${HOME}/project/v2rayN/Release/linux-arm64" && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r linux-x64   -p:SelfContained=true -o "$OutputPath64" && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r linux-arm64 -p:SelfContained=true -o "$OutputPathArm64" && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r linux-x64   -p:SelfContained=true -p:PublishTrimmed=true -o "$OutputPath64" && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r linux-arm64 -p:SelfContained=true -p:PublishTrimmed=true -o "$OutputPathArm64" && \
        cd ${HOME}/project/v2rayN && \
        echo -e "\033[32m------------------------------ package debian ------------------------------\033[0m" && \
        release_tag="1.0.0" && \
        chmod 755 package-debian.sh && \
        ./package-debian.sh $OutputArch $OutputPath64 ${release_tag} && \
        ./package-debian.sh $OutputArchArm $OutputPathArm64 ${release_tag} && \
        echo -e "\033[32m------------------------------ package release zip archive ------------------------------\033[0m" && \
        chmod 755 package-release-zip.sh && \
        ./package-release-zip.sh $OutputArch $OutputPath64 && \
        ./package-release-zip.sh $OutputArchArm $OutputPathArm64 && \
        cd ${HOME}/project/v2rayN/v2rayN && \
        echo -e "\033[32m------------------------------ build osx ------------------------------\033[0m" && \
        OutputArch="macos-64" && \
        OutputArchArm="macos-arm64" && \
        OutputPath64="${HOME}/project/v2rayN/Release/macos-64" && \
        OutputPathArm64="${HOME}/project/v2rayN/Release/macos-arm64" && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r osx-x64   -p:SelfContained=true -o $OutputPath64 && \
        dotnet publish ./v2rayN.Desktop/v2rayN.Desktop.csproj -c Release -r osx-arm64 -p:SelfContained=true -o $OutputPathArm64 && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r osx-x64   -p:SelfContained=true -p:PublishTrimmed=true -o $OutputPath64 && \
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r osx-arm64 -p:SelfContained=true -p:PublishTrimmed=true -o $OutputPathArm64 && \
        cd ${HOME}/project/v2rayN && \
        echo -e "\033[32m------------------------------ package release zip archive ------------------------------\033[0m" && \
        chmod 755 package-release-zip.sh && \
        ./package-release-zip.sh $OutputArch $OutputPath64 && \
        ./package-release-zip.sh $OutputArchArm $OutputPathArm64 && \
        echo -e "\033[32mls -AlhF ${HOME}/project/v2rayN:\033[0m" && \
        ls -AlhF ${HOME}/project/v2rayN && \
        cd ${HOME}/project
        SCRIPT
        cat build-project.sh | docker run -i --rm ubuntu bash
