name: docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
  push:
    paths:
      - '.github/workflows/docker.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: docker
        run: |
          set -e
          sudo apt-get update &> /dev/null
          docker run hello-world &> log
          docker run -dit --rm ubuntu bash &>> log
          docker run -dit --rm ubuntu:26.04 bash &>> log
          cat << 'EOF' > Dockerfile
          FROM ubuntu
          WORKDIR /root
          RUN apt-get update > /dev/null 2>&1 && \
              apt-get upgrade -y > /dev/null 2>&1 && \
              apt-get autoremove -y > /dev/null 2>&1 && \
              apt-get install -y unminimize > /dev/null 2>&1 && \
              printf '%b' 'y\n' | unminimize > /dev/null 2>&1 && \
              printf '%b' '5\n68\n' | script -q -c 'apt-get install -y tzdata' /dev/null && \
              apt-get install -y sudo man-db command-not-found bash-completion vim neovim g++ cmake cgdb git wget curl zip unzip 7zip tree tmux htop calc language-pack-zh-hans openssh-server > /dev/null 2>&1 && \
              apt-get update > /dev/null 2>&1
          EOF
          docker build -t temp . &>> log
          grep log 'Current default time zone'
          cat << 'CMD' | docker run -i --rm temp bash
          echo "--------------------------------------------------------------------" && \
          nvim --version && \
          echo "--------------------------------------------------------------------" && \
          g++ --version && \
          echo "--------------------------------------------------------------------" && \
          which python3 && \
          $(which python3) --version
          CMD
          echo "--------------------------------------------------------------------" && \
          docker images
          grep 'Digest' log | awk -F'sha256:' '{print substr($2,1,12)}' | tee sum
          grep -q '4' sum
