name: docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
  push:
    paths:
      - '.github/workflows/docker.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: docker
        run: |
          set -e
          docker run hello-world &> /dev/null
          docker run -dit --rm ubuntu bash &> /dev/null
          docker images
          cat << 'EOF' > Dockerfile
          FROM ubuntu:26.04
          RUN apt-get update > /dev/null 2>&1 && \
              apt-get upgrade -y > /dev/null 2>&1 && \
              printf '5\n68\n' | script -q -c "apt-get install -y tzdata" /dev/null && \
              apt-get install -y sudo man-db command-not-found bash-completion vim neovim g++ cmake cgdb git wget curl zip unzip 7zip tree tmux htop calc language-pack-zh-hans openssh-server > /dev/null 2>&1 && \
              echo "--------------------------------------------------------------------" && \
              nvim --version && \
              echo "--------------------------------------------------------------------" && \
              g++ --version && \
              echo "--------------------------------------------------------------------" && \
              python3 --version
          EOF
          cat Dockerfile
          docker build -t temp .
