name: dump

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/dump.yml'
      - 'test/sort-gcc.cpp'
      - 'test/sort-general.cpp'

env:
  GCC_VERSION: 15.2.0
  CLANG_VERSION: 21.1.8

jobs:
  ubuntu-gcc-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ubuntu gcc ${{ env.GCC_VERSION }}
        run: |
          set -e
          sudo apt-get update &> /dev/null
          sudo apt-get install -y wget g++ libmpc-dev make flex &> /dev/null
          curl -fsSL -O https://github.com/gcc-mirror/gcc/archive/refs/tags/releases/gcc-${GCC_VERSION}.tar.gz
          tar -zxf gcc-${GCC_VERSION}.tar.gz
          rm gcc-${GCC_VERSION}.tar.gz
          cd gcc-releases-gcc-${GCC_VERSION}
          mkdir build
          cd build
          ../configure --disable-multilib &> /dev/null
          make -j$(nproc) &> /dev/null
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ \
            -B${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/libstdc++-v3/libsupc++ \
            -L${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs \
            ${GITHUB_WORKSPACE}/test/sort-general.cpp
          ./a.out
          rm a.out
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ \
            -B${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/libstdc++-v3/libsupc++ \
            -L${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs \
            ${GITHUB_WORKSPACE}/test/sort-gcc.cpp
          ./a.out
          rm a.out
          echo -e "\033[32m------------------------------ single output ------------------------------\033[0m"
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v
          echo -e "\033[32m------------------------------ {} output ------------------------------\033[0m"
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v
          }
          echo -e "\033[32m------------------------------ {} 2>&1 output ------------------------------\033[0m"
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v
          } 2>&1

  ubuntu-gcc-dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ubuntu gcc ${{ env.GCC_VERSION }}
        run: |
          set -e
          sudo apt-get update &> /dev/null
          sudo apt-get install -y wget g++ libmpc-dev make flex &> /dev/null
          curl -fsSL -O https://github.com/gcc-mirror/gcc/archive/refs/tags/releases/gcc-${GCC_VERSION}.tar.gz
          tar -zxf gcc-${GCC_VERSION}.tar.gz
          rm gcc-${GCC_VERSION}.tar.gz
          cd gcc-releases-gcc-${GCC_VERSION}
          mkdir build
          cd build
          ../configure --disable-multilib &> /dev/null
          make -j$(nproc) &> /dev/null
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ \
            -B${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/libstdc++-v3/libsupc++ \
            -L${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs \
            ${GITHUB_WORKSPACE}/test/sort-general.cpp
          ./a.out
          rm a.out
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ \
            -B${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/libstdc++-v3/libsupc++ \
            -L${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs \
            ${GITHUB_WORKSPACE}/test/sort-gcc.cpp
          ./a.out
          rm a.out
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m" > log1
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version >> log1
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m" >> log1
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v >> log1 2> /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m" > log2
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version 2>> log2 > /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m" >> log2
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v 2>> log2
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m" > log3
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version >> log3 2>&1
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m" >> log3
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v >> log3 2>&1
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m" > log4
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version &>> log4
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m" >> log4
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v &>> log4
          echo -e "\033[32m------------------------------ single >> log ------------------------------\033[0m"
          cat log1
          echo -e "\033[32m------------------------------ single 2>> log ------------------------------\033[0m"
          cat log2
          echo -e "\033[32m------------------------------ single >> log 2>&1 ------------------------------\033[0m"
          cat log3
          echo -e "\033[32m------------------------------ single &>> log ------------------------------\033[0m"
          cat log4
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v 2> /dev/null
          } > log5
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m" >&2
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version > /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m" >&2
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v
          } 2> log6
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v
          } > log7 2>&1
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v
          } &> log8
          echo -e "\033[32m------------------------------ {} > log ------------------------------\033[0m"
          cat log5
          echo -e "\033[32m------------------------------ {} 2> log ------------------------------\033[0m"
          cat log6
          echo -e "\033[32m------------------------------ {} > log 2>&1 ------------------------------\033[0m"
          cat log7
          echo -e "\033[32m------------------------------ {} &> log ------------------------------\033[0m"
          cat log8

  ubuntu-clang-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ubuntu clang ${{ env.CLANG_VERSION }}
        run: |
          set -e
          sudo apt-get update &> /dev/null
          sudo apt-get install -y curl cmake ninja-build g++ python3 &> /dev/null
          curl -fsSL -O https://github.com/llvm/llvm-project/releases/download/llvmorg-${CLANG_VERSION}/llvm-project-${CLANG_VERSION}.src.tar.xz
          tar -xf llvm-project-${CLANG_VERSION}.src.tar.xz
          cd llvm-project-${CLANG_VERSION}.src
          mkdir build
          cd build
          cmake -G Ninja ../llvm -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind;libcxxabi;libcxx" &> /dev/null
          ninja &> /dev/null
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang++ ${GITHUB_WORKSPACE}/test/sort-general.cpp
          ./a.out
          rm a.out
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang++ ${GITHUB_WORKSPACE}/test/sort-gcc.cpp
          ./a.out
          rm a.out
          echo -e "\033[32m------------------------------ single output ------------------------------\033[0m"
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          echo -e "\033[32m------------------------------ {} output ------------------------------\033[0m"
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          }
          echo -e "\033[32m------------------------------ {} 2>&1 output ------------------------------\033[0m"
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          } 2>&1

  ubuntu-clang-dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ubuntu clang ${{ env.CLANG_VERSION }}
        run: |
          set -e
          sudo apt-get update &> /dev/null
          sudo apt-get install -y curl cmake ninja-build g++ python3 &> /dev/null
          curl -fsSL -O https://github.com/llvm/llvm-project/releases/download/llvmorg-${CLANG_VERSION}/llvm-project-${CLANG_VERSION}.src.tar.xz
          tar -xf llvm-project-${CLANG_VERSION}.src.tar.xz
          cd llvm-project-${CLANG_VERSION}.src
          mkdir build
          cd build
          cmake -G Ninja ../llvm -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind;libcxxabi;libcxx" &> /dev/null
          ninja &> /dev/null
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang++ ${GITHUB_WORKSPACE}/test/sort-general.cpp
          ./a.out
          rm a.out
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang++ ${GITHUB_WORKSPACE}/test/sort-gcc.cpp
          ./a.out
          rm a.out
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m" > log1
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version >> log1
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m" >> log1
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v >> log1 2> /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m" > log2
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version 2>> log2 > /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m" >> log2
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v 2>> log2
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m" > log3
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version >> log3 2>&1
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m" >> log3
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v >> log3 2>&1
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m" > log4
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version &>> log4
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m" >> log4
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v &>> log4
          echo -e "\033[32m------------------------------ single >> log ------------------------------\033[0m"
          cat log1
          echo -e "\033[32m------------------------------ single 2>> log ------------------------------\033[0m"
          cat log2
          echo -e "\033[32m------------------------------ single >> log 2>&1 ------------------------------\033[0m"
          cat log3
          echo -e "\033[32m------------------------------ single &>> log ------------------------------\033[0m"
          cat log4
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v 2> /dev/null
          } > log5
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m" >&2
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version > /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m" >&2
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          } 2> log6
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          } > log7 2>&1
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          } &> log8
          echo -e "\033[32m------------------------------ {} 1 > log ------------------------------\033[0m"
          cat log5
          echo -e "\033[32m------------------------------ {} 2 > log ------------------------------\033[0m"
          cat log6
          echo -e "\033[32m------------------------------ {} > log 2>&1 ------------------------------\033[0m"
          cat log7
          echo -e "\033[32m------------------------------ {} &> log ------------------------------\033[0m"
          cat log8

  macos-gcc-output:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: macos default gcc
        run: |
          set -e
          which g++-15
          g++-15 ${GITHUB_WORKSPACE}/test/sort-general.cpp
          ./a.out
          rm a.out
          g++-15 ${GITHUB_WORKSPACE}/test/sort-gcc.cpp
          ./a.out
          rm a.out
          echo -e "\033[32m------------------------------ single output ------------------------------\033[0m"
          echo -e "\033[32mg++-15 --version:\033[0m"
          g++-15 --version
          echo -e "\033[32mg++-15 -v:\033[0m"
          g++-15 -v
          echo -e "\033[32m------------------------------ {} output ------------------------------\033[0m"
          {
          echo -e "\033[32mg++-15 --version:\033[0m"
          g++-15 --version
          echo -e "\033[32mg++-15 -v:\033[0m"
          g++-15 -v
          }
          echo -e "\033[32m------------------------------ {} 2>&1 output ------------------------------\033[0m"
          {
          echo -e "\033[32mg++-15 --version:\033[0m"
          g++-15 --version
          echo -e "\033[32mg++-15 -v:\033[0m"
          g++-15 -v
          } 2>&1

  macos-gcc-dump:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: macos default gcc
        run: |
          set -e
          which g++-15
          g++-15 ${GITHUB_WORKSPACE}/test/sort-general.cpp
          ./a.out
          rm a.out
          g++-15 ${GITHUB_WORKSPACE}/test/sort-gcc.cpp
          ./a.out
          rm a.out
          echo -e "\033[32mg++-15 --version:\033[0m" > log1
          g++-15 --version >> log1
          echo -e "\033[32mg++-15 -v:\033[0m" >> log1
          g++-15 -v >> log1 2> /dev/null
          echo -e "\033[32mg++-15 --version:\033[0m" > log2
          g++-15 --version 2>> log2 > /dev/null
          echo -e "\033[32mg++-15 -v:\033[0m" >> log2
          g++-15 -v 2>> log2
          echo -e "\033[32mg++-15 --version:\033[0m" > log3
          g++-15 --version >> log3 2>&1
          echo -e "\033[32mg++-15 -v:\033[0m" >> log3
          g++-15 -v >> log3 2>&1
          echo -e "\033[32m------------------------------ single >> log ------------------------------\033[0m"
          cat log1
          echo -e "\033[32m------------------------------ single 2>> log ------------------------------\033[0m"
          cat log2
          echo -e "\033[32m------------------------------ single >> log 2>&1 ------------------------------\033[0m"
          cat log3
          {
          echo -e "\033[32mg++-15 --version:\033[0m"
          g++-15 --version
          echo -e "\033[32mg++-15 -v:\033[0m"
          g++-15 -v 2> /dev/null
          } > log4
          {
          echo -e "\033[32mg++-15 --version:\033[0m" >&2
          g++-15 --version > /dev/null
          echo -e "\033[32mg++-15 -v:\033[0m" >&2
          g++-15 -v
          } 2> log5
          {
          echo -e "\033[32mg++-15 --version:\033[0m"
          g++-15 --version
          echo -e "\033[32mg++-15 -v:\033[0m"
          g++-15 -v
          } > log6 2>&1
          {
          echo -e "\033[32mg++-15 --version:\033[0m"
          g++-15 --version
          echo -e "\033[32mg++-15 -v:\033[0m"
          g++-15 -v
          } &> log7
          echo -e "\033[32m------------------------------ {} > log ------------------------------\033[0m"
          cat log4
          echo -e "\033[32m------------------------------ {} 2> log ------------------------------\033[0m"
          cat log5
          echo -e "\033[32m------------------------------ {} > log 2>&1 ------------------------------\033[0m"
          cat log6
          echo -e "\033[32m------------------------------ {} &> log ------------------------------\033[0m"
          cat log7

  macos-clang-output:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: macos clang ${{ env.CLANG_VERSION }}
        run: |
          set -e
          curl -fsSL -O https://github.com/llvm/llvm-project/releases/download/llvmorg-${CLANG_VERSION}/llvm-project-${CLANG_VERSION}.src.tar.xz
          tar -xf llvm-project-${CLANG_VERSION}.src.tar.xz
          cd llvm-project-${CLANG_VERSION}.src
          mkdir build
          cd build
          cmake -G Ninja ../llvm -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind;libcxxabi;libcxx" > /dev/null 2>&1
          ninja > /dev/null 2>&1
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang++ --sysroot=$(xcrun --sdk macosx --show-sdk-path) ${GITHUB_WORKSPACE}/test/sort-general.cpp
          ./a.out
          rm a.out
          echo -e "\033[32m------------------------------ single output ------------------------------\033[0m"
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          echo -e "\033[32m------------------------------ {} output ------------------------------\033[0m"
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          }
          echo -e "\033[32m------------------------------ {} 2>&1 output ------------------------------\033[0m"
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          } 2>&1

  macos-clang-dump:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: macos clang ${{ env.CLANG_VERSION }}
        run: |
          set -e
          curl -fsSL -O https://github.com/llvm/llvm-project/releases/download/llvmorg-${CLANG_VERSION}/llvm-project-${CLANG_VERSION}.src.tar.xz
          tar -xf llvm-project-${CLANG_VERSION}.src.tar.xz
          cd llvm-project-${CLANG_VERSION}.src
          mkdir build
          cd build
          cmake -G Ninja ../llvm -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind;libcxxabi;libcxx" > /dev/null 2>&1
          ninja > /dev/null 2>&1
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang++ --sysroot=$(xcrun --sdk macosx --show-sdk-path) ${GITHUB_WORKSPACE}/test/sort-general.cpp
          ./a.out
          rm a.out
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m" > log1
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version >> log1
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m" >> log1
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v >> log1 2> /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m" > log2
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version 2>> log2 > /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m" >> log2
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v 2>> log2
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m" > log3
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version >> log3 2>&1
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m" >> log3
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v >> log3 2>&1
          echo -e "\033[32m------------------------------ single >> log ------------------------------\033[0m"
          cat log1
          echo -e "\033[32m------------------------------ single 2>> log ------------------------------\033[0m"
          cat log2
          echo -e "\033[32m------------------------------ single >> log 2>&1 ------------------------------\033[0m"
          cat log3
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v 2> /dev/null
          } > log4
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m" >&2
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version > /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m" >&2
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          } 2> log5
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          } > log6 2>&1
          {
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          } &> log7
          echo -e "\033[32m------------------------------ {} > log ------------------------------\033[0m"
          cat log4
          echo -e "\033[32m------------------------------ {} 2> log ------------------------------\033[0m"
          cat log5
          echo -e "\033[32m------------------------------ {} > log 2>&1 ------------------------------\033[0m"
          cat log6
          echo -e "\033[32m------------------------------ {} &> log ------------------------------\033[0m"
          cat log7
