name: gcc-clang

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/gcc-clang.yml'

env:
  GCC_VERSION: 15.2.0
  CLANG_VERSION: 21.1.8

jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: gcc ${{ env.GCC_VERSION }}
        run: |
          sudo apt-get update &> /dev/null
          sudo apt-get install -y wget g++ libmpc-dev make flex &> /dev/null
          curl -fsSL -O https://github.com/gcc-mirror/gcc/archive/refs/tags/releases/gcc-${GCC_VERSION}.tar.gz
          tar -zxf gcc-${GCC_VERSION}.tar.gz
          rm gcc-${GCC_VERSION}.tar.gz
          cd gcc-releases-gcc-${GCC_VERSION}
          mkdir build
          cd build
          ../configure --disable-multilib &> /dev/null
          make -j$(nproc) &> /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v:\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ -v
          echo -e "\033[32m------------------------------ build sort-general.cpp ------------------------------\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ \
            -B${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/libstdc++-v3/libsupc++ \
            -L${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs \
            ${GITHUB_WORKSPACE}/sort-general.cpp
          ./a.out
          rm a.out
          echo -e "\033[32m------------------------------ build sort-gcc.cpp ------------------------------\033[0m"
          ${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc/xg++ \
            -B${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/gcc \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/include \
            -I${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/libstdc++-v3/libsupc++ \
            -L${GITHUB_WORKSPACE}/gcc-releases-gcc-${GCC_VERSION}/build/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs \
            ${GITHUB_WORKSPACE}/sort-gcc.cpp
          ./a.out

  ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ubuntu clang ${{ env.CLANG_VERSION }}
        run: |
          set -e
          sudo apt-get update &> /dev/null
          sudo apt-get install -y curl cmake ninja-build g++ python3 &> /dev/null
          curl -fsSL -O https://github.com/llvm/llvm-project/releases/download/llvmorg-${CLANG_VERSION}/llvm-project-${CLANG_VERSION}.src.tar.xz
          tar -xf llvm-project-${CLANG_VERSION}.src.tar.xz
          cd llvm-project-${CLANG_VERSION}.src
          mkdir build
          cd build
          cmake -G Ninja ../llvm -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;cross-project-tests;lld;lldb;mlir;polly" \
            -DLLVM_ENABLE_RUNTIMES="libc;libunwind;libcxxabi;libcxx;compiler-rt;openmp;offload;libclc" &> /dev/null
          ninja &> /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          echo -e "\033[32m------------------------------ sort-general.cpp ------------------------------\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang++ ${GITHUB_WORKSPACE}/sort-general.cpp
          ./a.out
          rm a.out
          echo -e "\033[32m------------------------------ sort-gcc.cpp ------------------------------\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang++ ${GITHUB_WORKSPACE}/sort-gcc.cpp
          ./a.out

  macos-clang:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: macos clang ${{ env.CLANG_VERSION }}
        run: |
          set -e
          curl -fsSL -O https://github.com/llvm/llvm-project/releases/download/llvmorg-${CLANG_VERSION}/llvm-project-${CLANG_VERSION}.src.tar.xz
          tar -xf llvm-project-${CLANG_VERSION}.src.tar.xz
          cd llvm-project-${CLANG_VERSION}.src
          mkdir build
          cd build
          cmake -G Ninja ../llvm -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind;libcxxabi;libcxx" &> /dev/null
          ninja &> /dev/null
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang --version
          echo -e "\033[32m${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v:\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang -v
          echo -e "\033[32m------------------------------ build sort-general.cpp ------------------------------\033[0m"
          ${GITHUB_WORKSPACE}/llvm-project-${CLANG_VERSION}.src/build/bin/clang++ --sysroot=$(xcrun --sdk macosx --show-sdk-path) ${GITHUB_WORKSPACE}/sort-general.cpp
          ./a.out
