name: temp

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/temp.yml'

jobs:
  temp:
    runs-on: ubuntu-latest
    steps:
    - name: temp
      run: |
        date
        df -h
        sudo apt-get update && \
        sudo apt-get install -y python3-venv && \
        mkdir ~/tools && \
        cd ~/tools && \
        wget https://github.com/neovim/neovim/releases/download/v0.11.6/nvim-linux-x86_64.tar.gz && \
        tar -zxf nvim-linux-x86_64.tar.gz && \
        rm nvim-linux-x86_64.tar.gz && \
        echo 'export PATH=$PATH:${HOME}/tools/nvim-linux-x86_64/bin' >> ~/.bashrc && \
        git clone https://github.com/LazyVim/starter ~/.config/nvim && \
        {
        cat << 'BASIC_LUA' >> ~/.config/nvim/lua/config/basic.lua
        vim.opt.expandtab = true
        vim.opt.shiftwidth = 4
        vim.opt.relativenumber = false
        vim.opt.guicursor = "a:ver25"
        vim.opt.selection = "inclusive"
        vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "NONE", bg = "NONE" })
        vim.keymap.set({'v', 'x'}, '<C-c>', '"+y', { silent = true })
        vim.keymap.set({'n', 'v'}, '<C-v>', '"+p', { silent = true })
        vim.keymap.set('i', '<C-v>', '<C-r>+', { silent = true })
        BASIC_LUA
        } && \
        echo >> ~/.config/nvim/init.lua && \
        echo 'require("config.basic")' >> ~/.config/nvim/init.lua && \
        {
        cat << 'MASON_LUA' >> ~/.config/nvim/lua/plugins/mason.lua
        return {
          "WhoIsSethDaniel/mason-tool-installer.nvim",
          dependencies = { "mason-org/mason.nvim" },
          opts = {
            run_on_start = true,
            ensure_installed = {
              "cpptools",
              "clangd",
              "clang-format",
            },
          },
        }
        MASON_LUA
        } && \
        {
        cat << 'BLINK_LUA' >> ~/.config/nvim/lua/plugins/blink.lua
        return {
          {
            "saghen/blink.cmp",
            opts = {
              keymap = {
                ["<CR>"] = false,                          -- 禁用 Enter 确认
                ["<Tab>"] = { "accept", "fallback" },      -- Tab 确认补全 / 否则缩进
                ["<C-n>"] = { "select_next", "fallback" }, -- 下一个候选
                ["<C-p>"] = { "select_prev", "fallback" }, -- 上一个候选
                ["<C-Space>"] = { "show", "fallback" },    -- 手动触发补全
                ["<Esc>"] = { "hide", "fallback" },        -- 关闭补全框
              },
            },
          },
        }
        BLINK_LUA
        } && \
        source ~/.bash_alias && \
        nvim -c 'q'
