name: v2rayN version

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/v2rayN-version.yml'

jobs:
  check-version:
    runs-on: ubuntu-latest
    env:
      V2RAYN_VERSION: 7.2.3
    steps:
    - name: Check version
      run: |
        set -e
        sudo apt-get update > /dev/null
        sudo apt-get install -y wget unzip wine &> /dev/null
        echo -e "\033[32m-------------------------------- v2rayN ${V2RAYN_VERSION} --------------------------------\033[0m"
        IFS='.' read -r a b c <<< "${V2RAYN_VERSION}" && \
        if [ "$a" -gt 7 ] || { [ "$a" -eq 7 ] && [ "$b" -ge 9 ]; }; then
          wget -q https://github.com/2dust/v2rayN/releases/download/${V2RAYN_VERSION}/v2rayN-windows-64-desktop.zip
          unzip -q v2rayN-windows-64-desktop.zip
          mv ${GITHUB_WORKSPACE}/v2rayN-windows-64 ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop
          echo -e "\033[35mv2rayN-windows-64-desktop:\033[0m"
          echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/mihomo/mihomo*.exe -v:\033[0m"
          wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/mihomo/mihomo*.exe -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
          echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/sing_box/sing-box.exe version:\033[0m"
          wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/sing_box/sing-box.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
          echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/xray/xray.exe version:\033[0m"
          wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
          echo -e "\033[32m--------------------------------------------------------------------------------\033[0m"
        fi
        if [ "$a" -eq 7 ]; then
          if [ "$b" -lt 7 ]; then
            if [ "$b" -lt 5 ]; then
              wget -q https://github.com/2dust/v2rayN/releases/download/${V2RAYN_VERSION}/v2rayN-windows-64-With-Core.7z
              7z x v2rayN-windows-64With-Core.7z > /dev/null
              wget -q https://github.com/2dust/v2rayN/releases/download/${V2RAYN_VERSION}/v2rayN-windows-64-SelfContained-With-Core.7z
              7z x v2rayN-windows-64-SelfContained-With-Core.7z > /dev/null
            else
              wget -q https://github.com/2dust/v2rayN/releases/download/${V2RAYN_VERSION}/v2rayN-windows-64-With-Core.zip
              unzip -q v2rayN-windows-64-With-Core.zip
              wget -q https://github.com/2dust/v2rayN/releases/download/${V2RAYN_VERSION}/v2rayN-windows-64-SelfContained-With-Core.zip
              unzip -q v2rayN-windows-64-SelfContained-With-Core.zip
            fi
            echo -e "\033[35mv2rayN-windows-64-With-Core:\033[0m"
            echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/mihomo/mihomo*.exe -v:\033[0m"
            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/mihomo/mihomo*.exe -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
            echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/sing_box/sing-box.exe version:\033[0m"
            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/sing_box/sing-box.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
            echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/xray/xray.exe version:\033[0m"
            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
            echo -e "\033[32m--------------------------------------------------------------------------------\033[0m"
            echo -e "\033[35mv2rayN-windows-64-SelfContained-With-Core:\033[0m"
            echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/mihomo/mihomo*.exe -v:\033[0m"
            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/mihomo/mihomo*.exe -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
            echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/sing_box/sing-box.exe version:\033[0m"
            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/sing_box/sing-box.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
            echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/xray/xray.exe version:\033[0m"
            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
            echo -e "\033[32m--------------------------------------------------------------------------------\033[0m"
          elif [ "$b" -ge 7 ]; then
            wget -q https://github.com/2dust/v2rayN/releases/download/${V2RAYN_VERSION}/v2rayN-windows-64.zip
            unzip -q v2rayN-windows-64.zip
            echo -e "\033[35mv2rayN-windows-64:\033[0m"
            echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/mihomo/mihomo*.exe -v:\033[0m"
            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/mihomo/mihomo*.exe -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
            echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/sing_box/sing-box.exe version:\033[0m"
            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/sing_box/sing-box.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
            echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/xray/xray.exe version:\033[0m"
            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
            echo -e "\033[32m--------------------------------------------------------------------------------\033[0m"
            if [ "$b" -lt 18 ]; then
              wget -q https://github.com/2dust/v2rayN/releases/download/${V2RAYN_VERSION}/v2rayN-windows-64-SelfContained.zip
              unzip -q v2rayN-windows-64-SelfContained.zip
              echo -e "\033[35mv2rayN-windows-64-SelfContained:\033[0m"
              echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/mihomo/mihomo*.exe -v:\033[0m"
              wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/mihomo/mihomo*.exe -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
              echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/sing_box/sing-box.exe version:\033[0m"
              wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/sing_box/sing-box.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
              echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/xray/xray.exe version:\033[0m"
              wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
              echo -e "\033[32m--------------------------------------------------------------------------------\033[0m"
            fi
          fi
        fi
        wget -q https://github.com/2dust/v2rayN/releases/download/${V2RAYN_VERSION}/v2rayN-linux-64.zip
        unzip -q v2rayN-linux-64.zip
        echo -e "\033[35mv2rayN-linux-64:\033[0m"
        chmod +x ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/mihomo/mihomo
        echo -e "\033[32m${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/mihomo/mihomo -v:\033[0m"
        ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/mihomo/mihomo -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
        chmod +x ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/sing_box/sing-box
        echo -e "\033[32m${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/sing_box/sing-box version:\033[0m"
        ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/sing_box/sing-box version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
        chmod +x ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/xray/xray
        echo -e "\033[32m${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/xray/xray version:\033[0m"
        ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/xray/xray version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
